<?php

namespace Web\CompanyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComapnyCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyCategoryRepository extends EntityRepository
{
}