parameters:
#    web_company.example.class: Web\CompanyBundle\Example

services:
#    web_company.example:
#        class: %web_company.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
